
<!-- Old head functionality


<link rel="stylesheet" type="text/css" href="../bo/adminCommon/styles/<% out.print(backOffice.getStyleConfig().style);%>/css/backOffice.css" />

<title><%  out.print(pageTitle); %></title>

<script type="text/html" src="../bo/adminCommon/styles/<% out.print(backOffice.getStyleConfig().style);%>/scripts.inc"></script>

< %@ include file="../scripts/scripts.inc" %>

-->

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title><%  out.print(pageTitle); %></title>
<link rel="stylesheet" type="text/css" href="../bo/adminCommon/styles/bootstrap/css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="../bo/adminCommon/styles/bootstrap/css/backOffice.css"/>
<!--[if IE 9]>
    <link rel="stylesheet" media="screen" href="../bo/adminCommon/styles/bootstrap/css/ie9.css"/>
<![endif]-->

<!--[if IE 8]>
    <link rel="stylesheet" media="screen" href="../bo/adminCommon/styles/bootstrap/css/ie8.css"/>
<![endif]-->

<!--[if IE 7]>
    <link rel="stylesheet" media="screen" href="../bo/adminCommon/styles/bootstrap/css/ie7.css"/>
<![endif]-->



<!--
    Changed this to the latest for autocomplete.
    <script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery-1.7.min.js"></script>

    <script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery.colorbox-min.js"></script>
    <script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery-ui-1.8.16.custom.min.js"></script>

<link rel="stylesheet" type="text/css" href="../bo/adminCommon/scripts/autocomplete/autocomplete.css"/>
<script type="text/javascript" src="../bo/adminCommon/scripts/autocomplete/autocomplete.js"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>


-->

<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">



<!--

 Trying to upgrade

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery.dataTables.min.js"></script>

-->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/custom/tables.js"></script>

<script type="text/javascript" src="../bo/adminCommon/scripts/js/custom/media.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/custom/elements.js"></script>



<script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery.effects.core.min.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery.effects.explode.min.js"></script>

<script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/colorpicker.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery.alerts.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/custom/general.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/plugins/jquery.jgrowl.js"></script>
<script type="text/javascript" src="../bo/adminCommon/scripts/js/custom/form.js"></script>





<!-- Date picker -->


<link href="../bo/adminCommon/scripts/datepicker/css/datepicker.css" rel="stylesheet">
<script type="text/javascript" src="../bo/adminCommon/scripts/datepicker/js/bootstrap-datepicker.js"></script>



<!-- Shadowbox -->

<link rel="stylesheet" type="text/css" href="../bo/adminCommon/scripts/shadowbox-303-base/shadowbox.css"/>
<script type="text/javascript" src="../bo/adminCommon/scripts/shadowbox-303-base/shadowbox.js"></script>
<script type="text/javascript">
Shadowbox.init({
    handleOversize: "resize",
    modal: true
});
</script>

<!-- End  shadowbox -->




<!--[if lt IE 9]>
	<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
