package reclassification;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Rereference - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class RereferenceTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Re-reference Log";
    public static final String TABLE = "Rereference";
    private static final String DESCRIPTION = "References that are manually added or deleted";

    public enum Columns {Name, Add, Project, Document, FragmentNo, Fragment, ToFragment, Type, Closed, Date, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new BoolColumn("Add", DataColumn.narrowColumn),
            new StringColumn("Project", DataColumn.noFormatting),
            new StringColumn("Document", DataColumn.noFormatting),
            new IntColumn("FragmentNo", DataColumn.noFormatting),
            new BlobColumn("Fragment", DataColumn.noFormatting),
            new BlobColumn("ToFragment", DataColumn.noFormatting),
            new StringColumn("Type", DataColumn.noFormatting),
            new BoolColumn("Closed", DataColumn.narrowColumn),
            new DateColumn("Date", DataColumn.narrowColumn),
    };

    private static final Rereference associatedObject = new Rereference();
    public RereferenceTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public RereferenceTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {




    };

    @Override
    public void clearConstantCache(){

        Rereference.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
