package reclassification;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Rerisk - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ReriskTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Rerisk Log";
    public static final String TABLE = "Rerisk";
    private static final String DESCRIPTION = "Risk classifications that are manually added";

    public enum Columns {RiskLevel, Date, Project, Document, FragmentNo, Fragment, Pattern, PatternPos, User, Closed, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("RiskLevel", DataColumn.noFormatting),
            new DateColumn("Date", DataColumn.noFormatting),
            new StringColumn("Project", DataColumn.noFormatting),
            new StringColumn("Document", DataColumn.noFormatting),
            new IntColumn("FragmentNo", DataColumn.noFormatting),
            new BlobColumn("Fragment", DataColumn.noFormatting),
            new TextColumn("Pattern", DataColumn.noFormatting),
            new IntColumn("PatternPos", DataColumn.noFormatting),
            new StringColumn("User", DataColumn.noFormatting),
            new BoolColumn("Closed", DataColumn.narrowColumn),
    };

    private static final Rerisk associatedObject = new Rerisk();
    public ReriskTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ReriskTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {




    };

    @Override
    public void clearConstantCache(){

        Rerisk.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
