package actions;

import contractManagement.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ActionStatus - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ActionStatusTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Action Status";
    public static final String TABLE = "ActionStatus";
    private static final String DESCRIPTION = "Status updates and changes for a document";

    public enum Columns {Name, Ordinal, Comment, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new IntColumn("Ordinal", DataColumn.noFormatting),
            new TextColumn("Comment", DataColumn.noFormatting),
    };

    private static final ActionStatus associatedObject = new ActionStatus();
    public ActionStatusTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        setIsConstant();
    }

    public ActionStatusTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"Open", "1", "Action created but not assigned", "system"},
          {"In Progress", "3", "Action started", "system"},
          {"Completed", "5", "Work completed", "system"},
          {"Blocked", "4", "Waiting for external factors", "system"},
          {"Cancelled", "6", "No action needed", "system"},
          {"Done", "7", "Completed and approved", "system"},



    };
    private static final String[][] TestValues = {




    };

    @Override
    public void clearConstantCache(){

        ActionStatus.clearConstantCache();
    }

    private static Map<String, String> constantMap = null;


    @Override
    public Map<String, String> getConstantMap(){

        if(constantMap == null)
            constantMap = asNameMap();
        return constantMap;

    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
