package crossReference;

import dataRepresentation.*;

import java.util.ArrayList;
import java.util.List;

/********************************************************
 *
 *    ReferenceType - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ReferenceTypeTableConstant extends ConstantTable implements DataTableInterface{

    private static final String TITLE = "Reference Type";
    public static final String TABLE = "ReferenceType";
    private static final String DESCRIPTION = "Type of reference";

    public enum Columns {Name, Description, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final ReferenceType associatedObject = new ReferenceType();
    public ReferenceTypeTableConstant(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, Values2);
         /* No name column set for table. Using default ( 1 ) */
    }

    private static final List<DataObjectInterface> Values2 = new ArrayList<DataObjectInterface>(){{

            add(new ReferenceType(1, "Unknown", "Unknown or unclassified reference"));
            add(new ReferenceType(2, "Explicit", "An explicit reference to another clause or document"));
            add(new ReferenceType(3, "Implicit", "An implicit or derived reference"));
            add(new ReferenceType(4, "Definition Usage", "A reference to a definition"));
            add(new ReferenceType(5, "Open", "A link to external or unknown destination"));

    }};



    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
