package userManagement;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Group - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class Group extends DataObject implements DataObjectInterface{

    private static Group User = null;  


    private static final DataTableInterface TABLE = (DataTableInterface) new GroupTable();

    public Group(){

        super();

        if(table == null)
            table = TABLE;
    }

    public Group(String name, String description, DataObjectInterface organization) throws BackOfficeException{

        this(name, description, organization.getKey());
    }


    public Group(String name, String description, DBKeyInterface organization){

        this();
        try{
           ColumnStructureInterface[] columns = getColumnFromTable();


           data = new ColumnDataInterface[columns.length];

           data[0] = new StringData(name);
           data[1] = new TextData(description);
           data[2] = new ReferenceData(organization, columns[2].getTableReference());

           exists = true;
        }catch(BackOfficeException e){
            PukkaLogger.log(PukkaLogger.Level.FATAL, "Could not create object.");
            exists = false;
        }


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public Group(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        Group o = new Group();
        o.data = data;
        o.exists = true;
        return o;
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public String getDescription(){

        TextData data = (TextData) this.data[1];
        return data.getStringValue();
    }

    public void setDescription(String description){

        TextData data = (TextData) this.data[1];
        data.setStringValue(description);
    }



    public DBKeyInterface getOrganizationId(){

        ReferenceData data = (ReferenceData)this.data[2];
        return data.value;
    }

    public Organization getOrganization(){

        ReferenceData data = (ReferenceData)this.data[2];
        return new Organization(new LookupByKey(data.value));
    }

    public void setOrganization(DBKeyInterface organization){

        ReferenceData data = (ReferenceData)this.data[2];
        data.value = organization;
    }



    public static Group getUser( )  throws BackOfficeException{

       if(Group.User == null)
          Group.User = new Group(new LookupItem().addFilter(new ColumnFilter("Name", "User")));
       if(!Group.User.exists())
          throw new BackOfficeException(BackOfficeException.TableError, "Constant User is missing (db update required?)");

       return Group.User;
    }


    public static void clearConstantCache(){

        //  Clear all cache when the application is uploaded.

        Group.User = null;
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
