package userManagement;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    PortalUser - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class PortalUserTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "User";
    public static final String TABLE = "PortalUser";
    private static final String DESCRIPTION = "All registered users.";

    public enum Columns {Name, UserId, Type, Email, Registration, Organization, Active, WSAdmin, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new IntColumn("UserId", DataColumn.noFormatting),
            new StringColumn("Type", DataColumn.noFormatting),
            new StringColumn("Email", DataColumn.noFormatting),
            new DateColumn("Registration", DataColumn.noFormatting),
            new ReferenceColumn("Organization", DataColumn.noFormatting, new TableReference("Organization", "Name")),
            new BoolColumn("Active", DataColumn.noFormatting),
            new BoolColumn("WSAdmin", DataColumn.noFormatting),
    };

    private static final PortalUser associatedObject = new PortalUser();
    public PortalUserTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public PortalUserTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"itClarifies", "0", "SYSTEM", "", "2014-01-01", "itClarifies", "true", "true", "system"},
          {"External", "0", "EXTERNAL", "", "2014-01-01", "itClarifies", "true", "true", "system"},
          {"<< Not set >>", "0", "EMPTY", "", "2014-01-01", "itClarifies", "true", "true", "system"},
          {"Super", "1", "REGISTERED", "", "2014-01-01", "itClarifies", "true", "true", "system"},



    };
    private static final String[][] TestValues = {

          {"itClarifies", "0", "SYSTEM", "", "2014-01-01", "demo.org", "true", "true", "system"},
          {"External", "0", "EXTERNAL", "", "2014-01-01", "demo.org", "true", "true", "system"},
          {"<< Not set >>", "0", "EMPTY", "", "2014-01-01", "demo.org", "true", "true", "system"},
          {"demo", "2", "REGISTERED", "demo@dev.null", "2014-01-01", "demo.org", "true", "false", "system"},
          {"admin", "3", "REGISTERED", "admin@dev.null", "2014-01-01", "demo.org", "true", "true", "system"},
          {"linus", "4", "REGISTERED", "linus@dev.null", "2014-01-01", "demo.org", "true", "true", "system"},
          {"ulf", "5", "REGISTERED", "ulf@dev.null", "2014-01-01", "demo.org", "true", "true", "system"},
          {"tolga", "6", "REGISTERED", "ulf@dev.null", "2014-01-01", "demo.org", "true", "true", "system"},
          {"henrik", "7", "REGISTERED", "ulf@dev.null", "2014-01-01", "demo.org", "true", "true", "system"},
          {"eve", "8", "REGISTERED", "eve@dev.null", "2014-01-01", "evil.org", "true", "true", "system"},



    };

    @Override
    public void clearConstantCache(){

        PortalUser.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/


}
