package versioning;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Snapshot - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class SnapshotTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Freeze Snapshot";
    public static final String TABLE = "Snapshot";
    private static final String DESCRIPTION = "Snapshot point for all documents";

    public enum Columns {Name, Project, Description, Creator, Timestamp, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new ReferenceColumn("Project", DataColumn.noFormatting, new TableReference("Project", "Name")),
            new TextColumn("Description", DataColumn.noFormatting),
            new ReferenceColumn("Creator", DataColumn.noFormatting, new TableReference("PortalUser", "Name")),
            new TimeStampColumn("Timestamp", DataColumn.noFormatting),
    };

    private static final Snapshot associatedObject = new Snapshot();
    public SnapshotTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public SnapshotTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"test freeze", "Demo", "test freeze for demo project", "admin", "2014-01-01 00:10:00", "system"},



    };

    @Override
    public void clearConstantCache(){

        Snapshot.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
