package project;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ProjectType - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 *
 */

public class ProjectTypeTable extends ConstantTable implements DataTableInterface{

    private static final String TITLE = "Project Type";
    public static final String TABLE = "ProjectType";
    private static final String DESCRIPTION = "Project Type";

    public enum Columns {Id, Name, Description, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new IntColumn("Id", DataColumn.noFormatting),
            new StringColumn("Name", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final ProjectType associatedObject = new ProjectType();
    public ProjectTypeTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, Values);
        nameColumn = 2;
    }

    public static final List<DataObjectInterface> Values = new ArrayList<DataObjectInterface>() {{

          add(new ProjectType(1, "Generic", "Unclassified"));
          add(new ProjectType(2, "Contracting", "itclarifies contracting framework"));



    }};

    public ProjectType getValue(int id){
        
        return (ProjectType)super.getConstantValue( id );
    }
    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
