package search;

import contractManagement.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Keyword - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class KeywordTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Contract Keywords";
    public static final String TABLE = "Keyword";
    private static final String DESCRIPTION = "Search completion keywords from the contract";

    public enum Columns {Keyword, Document, Project, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Keyword", DataColumn.noFormatting),
            new ReferenceColumn("Document", DataColumn.noFormatting, new TableReference("Contract", "Name")),
            new ReferenceColumn("Project", DataColumn.noFormatting, new TableReference("Project", "Name")),
    };

    private static final Keyword associatedObject = new Keyword();
    public KeywordTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public KeywordTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"GATC", "Google Analytics", "Demo", "system"},
          {"Account", "Google Analytics", "Demo", "system"},
          {"Hit", "Google Analytics", "Demo", "system"},
          {"Customer", "Google Analytics", "Demo", "system"},
          {"Customer Data", "Google Analytics", "Demo", "system"},
          {"Documentation", "Google Analytics", "Demo", "system"},
          {"billing account", "Google Analytics", "Demo", "system"},
          {"Profiles", "Google Analytics", "Demo", "system"},
          {"hit", "Google Analytics", "Demo", "system"},
          {"hits aggregated", "Google Analytics", "Demo", "system"},
          {"Confidential Information", "Google Analytics", "Demo", "system"},
          {"information disclosed", "Google Analytics", "Demo", "system"},
          {"confidential", "Google Analytics", "Demo", "system"},
          {"disclosed orally", "Google Analytics", "Demo", "system"},
          {"Processing Software Data", "Google Analytics", "Demo", "system"},
          {"hit may", "Google Analytics", "Demo", "system"},
          {"Google Analytics system", "Google Analytics", "Demo", "system"},
          {"Google Analytics-supported protocols", "Google Analytics", "Demo", "system"},
          {"Processing Software", "Google Analytics", "Demo", "system"},
          {"Software", "Google Analytics", "Demo", "system"},
          {"Profile", "Google Analytics", "Demo", "system"},
          {"report", "Google Analytics", "Demo", "system"},
          {"multiple profiles", "Google Analytics", "Demo", "system"},
          {"property", "Google Analytics", "Demo", "system"},
          {"property includes", "Google Analytics", "Demo", "system"},
          {"privacy policy", "Google Analytics", "Demo", "system"},
          {"servers", "Google Analytics", "Demo", "system"},
          {"third party", "Google Analytics", "Demo", "system"},
          {"visitor", "Google Analytics", "Demo", "system"},
          {"include", "Google Analytics", "Demo", "system"},



    };

    @Override
    public void clearConstantCache(){

        Keyword.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
