package contractManagement;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ContractVersionInstance - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ContractVersionInstanceTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Contract Version Instance";
    public static final String TABLE = "ContractVersionInstance";
    private static final String DESCRIPTION = "A specific version of a contract";

    public enum Columns {Version, Document, FileHandler, Creator, Creation, Fingerprint, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Version", DataColumn.noFormatting),
            new ReferenceColumn("Document", DataColumn.noFormatting, new TableReference("Contract", "Name")),
            new StringColumn("FileHandler", DataColumn.noFormatting),
            new ReferenceColumn("Creator", DataColumn.noFormatting, new TableReference("PortalUser", "Name")),
            new TimeStampColumn("Creation", DataColumn.noFormatting),
            new StringColumn("Fingerprint", DataColumn.noFormatting),
    };

    private static final ContractVersionInstance associatedObject = new ContractVersionInstance();
    public ContractVersionInstanceTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ContractVersionInstanceTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"Cannon v1.0", "Cannon", "no file", "demo", "2014-01-01 00:09:00", "123456", "system"},
          {"Google v1.0", "Google Analytics", "no file", "admin", "2014-01-01 00:09:00", "987654", "system"},



    };

    @Override
    public void clearConstantCache(){

        ContractVersionInstance.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



    public int getNextVersionForDocument(Contract document) throws BackOfficeException {

        return getCount(new LookupList().addFilter(new ReferenceFilter(Columns.Document.name(), document.getKey()))) + 1;

    }



}
