package contractManagement;

import risk.*;
import contractManagement.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ContractView - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ContractView extends DataObject implements DataObjectInterface{



    private static final DataTableInterface TABLE = (DataTableInterface) new ContractViewTable();

    public ContractView(){

        super();

        if(table == null)
            table = TABLE;
    }

    public ContractView(String name, DataObjectInterface contract, String search, String comment) throws BackOfficeException{

        this(name, contract.getKey(), search, comment);
    }


    public ContractView(String name, DBKeyInterface contract, String search, String comment){

        this();
        try{
           ColumnStructureInterface[] columns = getColumnFromTable();


           data = new ColumnDataInterface[columns.length];

           data[0] = new StringData(name);
           data[1] = new ReferenceData(contract, columns[1].getTableReference());
           data[2] = new TextData(search);
           data[3] = new TextData(comment);

           exists = true;
        }catch(BackOfficeException e){
            PukkaLogger.log(PukkaLogger.Level.FATAL, "Could not create object.");
            exists = false;
        }


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public ContractView(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        ContractView o = new ContractView();
        o.data = data;
        o.exists = true;
        return o;
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public DBKeyInterface getContractId(){

        ReferenceData data = (ReferenceData)this.data[1];
        return data.value;
    }

    public Contract getContract(){

        ReferenceData data = (ReferenceData)this.data[1];
        return new Contract(new LookupByKey(data.value));
    }

    public void setContract(DBKeyInterface contract){

        ReferenceData data = (ReferenceData)this.data[1];
        data.value = contract;
    }



    public String getSearch(){

        TextData data = (TextData) this.data[2];
        return data.getStringValue();
    }

    public void setSearch(String search){

        TextData data = (TextData) this.data[2];
        data.setStringValue(search);
    }



    public String getComment(){

        TextData data = (TextData) this.data[3];
        return data.getStringValue();
    }

    public void setComment(String comment){

        TextData data = (TextData) this.data[3];
        data.setStringValue(comment);
    }




    public static void clearConstantCache(){

        //  Clear all cache when the application is uploaded.

    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
