package contractManagement;

import contractManagement.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ContractRisk - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ContractRiskTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Risk Assessment";
    public static final String TABLE = "ContractRisk";
    private static final String DESCRIPTION = "Risk Classification of a contract fragment";

    public enum Columns {Name, Organization, Severity, Description, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new ReferenceColumn("Organization", DataColumn.noFormatting, new TableReference("Organization", "Name")),
            new IntColumn("Severity", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final ContractRisk associatedObject = new ContractRisk();
    public ContractRiskTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ContractRiskTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"Black", "itClarifies", "100", "Showstopper/blocker", "system"},
          {"Red", "itClarifies", "75", "Potentially expensive", "system"},
          {"Amber", "itClarifies", "50", "An elevated risk", "system"},
          {"Not Set", "itClarifies", "25", "unknown impact", "system"},
          {"No risk", "itClarifies", "0", "no risk", "system"},



    };
    private static final String[][] TestValues = {

          {"Blocker", "demo.org", "100", "Showstopper/blocker", "system"},
          {"High", "demo.org", "75", "Potentially expensive", "system"},
          {"Medium", "demo.org", "49", "An elevated risk", "system"},
          {"Potential", "demo.org", "25", "Unknown impact. To be classified", "system"},
          {"Not set", "demo.org", "0", "no risk classification done", "system"},
          {"Advantage", "demo.org", "-10", "A potential competitive advantage", "system"},



    };

    @Override
    public void clearConstantCache(){

        ContractRisk.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
