package contractManagement;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ContractClause - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ContractClauseTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Contract Clause";
    public static final String TABLE = "ContractClause";
    private static final String DESCRIPTION = "A clause or fragment";

    public enum Columns {Name, Version, Number, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new ReferenceColumn("Version", DataColumn.noFormatting, new TableReference("ContractVersionInstance", "Version")),
            new IntColumn("Number", DataColumn.noFormatting),
    };

    private static final ContractClause associatedObject = new ContractClause();
    public ContractClauseTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ContractClauseTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"Introduction", "Cannon v1.0", "1", "system"},
          {"Definition", "Cannon v1.0", "2", "system"},
          {"INTRODUCTION", "Google v1.0", "1", "system"},
          {"Definitions", "Google v1.0", "2", "system"},
          {"Fees and Service", "Google v1.0", "3", "system"},
          {"Member Account, Password, and Security", "Google v1.0", "4", "system"},
          {"Nonexclusive License", "Google v1.0", "5", "system"},
          {"Confidentiality", "Google v1.0", "6", "system"},
          {"Information Rights and Publicity", "Google v1.0", "7", "system"},
          {"Privacy", "Google v1.0", "8", "system"},
          {"Indemnification", "Google v1.0", "9", "system"},



    };

    @Override
    public void clearConstantCache(){

        ContractClause.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/


}
