package contractManagement;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    DocumentSection - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class DocumentSectionTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Document Section";
    public static final String TABLE = "DocumentSection";
    private static final String DESCRIPTION = "Sections for documents in a project";

    public enum Columns {Name, Ordinal, Description, Project, Owner, Access, Parent, Creation, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new IntColumn("Ordinal", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
            new ReferenceColumn("Project", DataColumn.noFormatting, new TableReference("Project", "Name")),
            new ReferenceColumn("Owner", DataColumn.noFormatting, new TableReference("PortalUser", "Name")),
            new ConstantColumn("Access", DataColumn.noFormatting, new TableReference("AccessRight", "Name")),
            new ReferenceColumn("Parent", DataColumn.noFormatting, new TableReference("DocumentSection", "Name")),
            new DateColumn("Creation", DataColumn.noFormatting),
    };

    private static final DocumentSection associatedObject = new DocumentSection();
    public DocumentSectionTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public DocumentSectionTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"All Documents", "0", "All documents", "Demo", "admin", "rwd", "All Documents", "2014-06-01", "system"},



    };

    @Override
    public void clearConstantCache(){

        DocumentSection.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
