package contractManagement;

import risk.*;
import contractManagement.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    Project - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ProjectTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Project";
    public static final String TABLE = "Project";
    private static final String DESCRIPTION = "A group of documents that are analyzed together";

    public enum Columns {Name, Description, Creator, Organization, CreationTime, Access, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
            new ReferenceColumn("Creator", DataColumn.noFormatting, new TableReference("PortalUser", "Name")),
            new ReferenceColumn("Organization", DataColumn.noFormatting, new TableReference("Organization", "Name")),
            new TimeStampColumn("CreationTime", DataColumn.noFormatting),
            new StringColumn("Access", DataColumn.noFormatting),
    };

    private static final Project associatedObject = new Project();
    public ProjectTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ProjectTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"Demo", "Test project", "admin", "demo.org", "2014-02-01", "Not used", "system"},
          {"Evil proj", "Test project", "eve", "evil.org", "2014-02-01", "Not used", "system"},



    };

    @Override
    public void clearConstantCache(){

        Project.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/





}
