package contractManagement;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    StructureItemType - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class StructureItemTypeTable extends ConstantTable implements DataTableInterface{

    private static final String TITLE = "Structure Item Type";
    public static final String TABLE = "StructureItemType";
    private static final String DESCRIPTION = "The type of the structural item";

    public enum Columns {Id, Name, Description, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new IntColumn("Id", DataColumn.narrowColumn),
            new StringColumn("Name", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final StructureItemType associatedObject = new StructureItemType();
    public StructureItemTypeTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, Values);
         /* No name column set for table. Using default ( 1 ) */
     }

    public static final List<DataObjectInterface> Values = new ArrayList<DataObjectInterface>() {{

          add(new StructureItemType(10, "Headline", "Headline"));
          add(new StructureItemType(20, "List", "List"));
          add(new StructureItemType(30, "List Item", "List item"));
          add(new StructureItemType(40, "FragmentGroup", "Fragment Group"));



    }};

    public StructureItemType getValue(int id){
        
        return (StructureItemType)super.getConstantValue( id );
    }
    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
