package risk;

import risk.*;
import contractManagement.*;
import userManagement.*;
import versioning.*;
import actions.*;
import search.*;
import crossReference.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ContractRisk - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ContractRiskTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Risk Assessment";
    public static final String TABLE = "ContractRisk";
    private static final String DESCRIPTION = "Risk Classification of a contract fragment";

    public enum Columns {Name, Severity, Description, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new IntColumn("Severity", DataColumn.noFormatting),
            new TextColumn("Description", DataColumn.noFormatting),
    };

    private static final ContractRisk associatedObject = new ContractRisk();
    public ContractRiskTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ContractRiskTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {

          {"Blocker", "100", "Showstopper/blocker", "system"},
          {"High", "75", "Potentially expensive", "system"},
          {"Medium", "25", "An elevated risk", "system"},
          {"Potential", "25", "unknown impact", "system"},
          {"No Risk", "0", "no risk", "system"},
          {"Not set", "0", "not set", "system"},
          {"Advantage", "-10", "A potential competitive advantage", "system"},



    };
    private static final String[][] TestValues = {




    };

    @Override
    public void clearConstantCache(){

        ContractRisk.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/

    public List<ContractRisk> getAll() throws BackOfficeException{

        loadFromDatabase();

        List<DataObjectInterface> objects = this.getValues();

        List<ContractRisk> list = (List<ContractRisk>)(List<?>) objects;

        return list;
    }




}
