package module;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ModuleTag - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ModuleTag extends DataObject implements DataObjectInterface{



    private static final DataTableInterface TABLE = (DataTableInterface) new ModuleTagTable();

    public ModuleTag(){

        super();

        if(table == null)
            table = TABLE;
    }

    public ModuleTag(String name, DataObjectInterface module, String tag) throws BackOfficeException{

        this(name, module.getKey(), tag);
    }


    public ModuleTag(String name, DBKeyInterface module, String tag){

        this();
        try{
           ColumnStructureInterface[] columns = getColumnFromTable();


           data = new ColumnDataInterface[columns.length];

           data[0] = new StringData(name);
           data[1] = new ReferenceData(module, columns[1].getTableReference());
           data[2] = new StringData(tag);

           exists = true;
        }catch(BackOfficeException e){
            PukkaLogger.log(PukkaLogger.Level.FATAL, "Could not create object.");
            exists = false;
        }


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public ModuleTag(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        ModuleTag o = new ModuleTag();
        o.data = data;
        o.exists = true;
        return o;
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public DBKeyInterface getModuleId(){

        ReferenceData data = (ReferenceData)this.data[1];
        return data.value;
    }

    public Module getModule(){

        ReferenceData data = (ReferenceData)this.data[1];
        return new Module(new LookupByKey(data.value));
    }

    public void setModule(DBKeyInterface module){

        ReferenceData data = (ReferenceData)this.data[1];
        data.value = module;
    }



    public String getTag(){

        StringData data = (StringData) this.data[2];
        return data.getStringValue();
    }

    public void setTag(String tag){

        StringData data = (StringData) this.data[2];
        data.setStringValue(tag);
    }




    public static void clearConstantCache(){

        //  Clear all cache when the application is uploaded.

    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
