package module;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ModuleProject - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ModuleProjectTable extends DataTable implements DataTableInterface{

    private static final String TITLE = "Module Project Usage";
    public static final String TABLE = "ModuleProject";
    private static final String DESCRIPTION = "Which modules are used in which projects";

    public enum Columns {Name, Module, Project, Timestamp, }

    private static final ColumnStructureInterface[] DATA = new ColumnStructureInterface[] {

            new StringColumn("Name", DataColumn.noFormatting),
            new ReferenceColumn("Module", DataColumn.noFormatting, new TableReference("Module", "Name")),
            new ReferenceColumn("Project", DataColumn.noFormatting, new TableReference("Project", "Name")),
            new TimeStampColumn("Timestamp", DataColumn.noFormatting),
    };

    private static final ModuleProject associatedObject = new ModuleProject();
    public ModuleProjectTable(){

        init(DATA, associatedObject, TABLE, TITLE, DESCRIPTION, DefaultValues, TestValues);
         /* No name column set for table. Using default ( 1 ) */
         // Not set as external
        // Not a constant table
    }

    public ModuleProjectTable(ConditionInterface condition){

        this();
        try{

            values = load(condition);
        }
        catch(BackOfficeException e){

            System.out.println("Error loading table values " + e.narration);
        }

    }
    private static final String[][] DefaultValues = {




    };
    private static final String[][] TestValues = {

          {"DemoContracting", "Contracting", "Demo", "2015-01-01", "system"},



    };

    @Override
    public void clearConstantCache(){

        ModuleProject.clearConstantCache();
    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
