package module;

import risk.*;
import contractManagement.*;
import classification.*;
import userManagement.*;
import project.*;
import versioning.*;
import actions.*;
import overviewExport.*;
import module.*;
import search.*;
import crossReference.*;
import reclassification.*;
import dataRepresentation.*;
import databaseLayer.DBKeyInterface;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import log.PukkaLogger;
import pukkaBO.exceptions.BackOfficeException;
import pukkaBO.condition.*;
import pukkaBO.database.*;

import pukkaBO.acs.*;

/********************************************************
 *
 *    ModuleProject - Data Object
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class ModuleProject extends DataObject implements DataObjectInterface{



    private static final DataTableInterface TABLE = (DataTableInterface) new ModuleProjectTable();

    public ModuleProject(){

        super();

        if(table == null)
            table = TABLE;
    }

    public ModuleProject(String name, DataObjectInterface module, DataObjectInterface project, String timestamp) throws BackOfficeException{

        this(name, module.getKey(), project.getKey(), timestamp);
    }


    public ModuleProject(String name, DBKeyInterface module, DBKeyInterface project, String timestamp){

        this();
        try{
           ColumnStructureInterface[] columns = getColumnFromTable();


           data = new ColumnDataInterface[columns.length];

           data[0] = new StringData(name);
           data[1] = new ReferenceData(module, columns[1].getTableReference());
           data[2] = new ReferenceData(project, columns[2].getTableReference());
           data[3] = new TimeStampData(timestamp);

           exists = true;
        }catch(BackOfficeException e){
            PukkaLogger.log(PukkaLogger.Level.FATAL, "Could not create object.");
            exists = false;
        }


    }
    /*********************************************************************''
     *
     *          Load from database
     *
     * @param condition - the SQL condition for selecting ONE UNIQUE object
     */

    public ModuleProject(ConditionInterface condition){

        this();

        try{
            exists = load(condition);

        }catch(BackOfficeException e){

            System.out.println("Error loading object from database" + e.narration);
            e.printStackTrace();
        }

    }

    public DataObjectInterface createNew(ColumnDataInterface[] data ) throws BackOfficeException {

        ModuleProject o = new ModuleProject();
        o.data = data;
        o.exists = true;
        return o;
    }

    public String getName(){

        StringData data = (StringData) this.data[0];
        return data.getStringValue();
    }

    public void setName(String name){

        StringData data = (StringData) this.data[0];
        data.setStringValue(name);
    }



    public DBKeyInterface getModuleId(){

        ReferenceData data = (ReferenceData)this.data[1];
        return data.value;
    }

    public Module getModule(){

        ReferenceData data = (ReferenceData)this.data[1];
        return new Module(new LookupByKey(data.value));
    }

    public void setModule(DBKeyInterface module){

        ReferenceData data = (ReferenceData)this.data[1];
        data.value = module;
    }



    public DBKeyInterface getProjectId(){

        ReferenceData data = (ReferenceData)this.data[2];
        return data.value;
    }

    public Project getProject(){

        ReferenceData data = (ReferenceData)this.data[2];
        return new Project(new LookupByKey(data.value));
    }

    public void setProject(DBKeyInterface project){

        ReferenceData data = (ReferenceData)this.data[2];
        data.value = project;
    }



    public DBTimeStamp getTimestamp()throws BackOfficeException{

        TimeStampData data = (TimeStampData) this.data[3];
        return new DBTimeStamp(DBTimeStamp.SQL_TIMESTAMP, data.value);
    }

    public void setTimestamp(DBTimeStamp timestamp){

        TimeStampData data = (TimeStampData) this.data[3];
        data.value = timestamp.getSQLTime().toString();
    }




    public static void clearConstantCache(){

        //  Clear all cache when the application is uploaded.

    }

    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
